import React from "react";
import HomeCity from "../../Components/HomeCity";
import Head from "next/head";

export default function Index({city}) {
  const Meta = ({ title, keywords, description }) => {
    return (
      <Head>
        <title>{title}</title>
        <meta httpEquiv="content-language" content="fr" />
        <meta name="language" content="fr" />
        <meta name="description" content={description} />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="keywords" content={keywords} />
        <meta charSet="utf-8" />
        <meta name="robots" content="index,follow" />
        <link
          rel="shortcut icon"
          type="image/png"
          href="/favicon.ico"
          title="icone"
        />
        <meta property="og:title" content="Redflower débarras" />
        <meta
          property="og:description"
          content={`Débarras maison appartement ${city.name} | devis gratuit`}
        />
        <meta property="og:url" content={`https://redflower-debarras.fr/${city.slug}`} />
        <meta property="og:type" content="website" />
        <link rel="icon" href="../../favicon.ico" />
        <link rel="canonical" href={`https://redflower-debarras.fr/${city.slug}`}/>
        <meta name="geo.placename" content="Lyon" />
        <meta name="msnbot" content="index,follow" />
        <meta name="ICBM" content="45.78498101131291, 4.7487209759413815" />
        <meta name="Geo.region" content="FR-69" />
      </Head>
    );
  };

  Meta.defaultProps = {
    title:
      `Débarras maison appartement ${city.name} | devis gratuit`,
    keywords:
      "débarras, entreprise, appartement, maison, enlèvement, biens, gratuit, rachat, valorisation, diogène, syllogomanie, succession, maison, garage, professionnel, monte-meuble, déménagement, Lyon, 69, 42, saint-etienne, Rhône, Auvergne-Rhône-Alpes, bourgogne",
    description:
      `Débarras appartement & maison ${city.preName} ${city.name} et sur tout types de superficies et locaux: local commercial, cave, grenier, grange, garage...`,
  };

  return (
    <>
      <Meta />
      <HomeCity city={city}/>
    </>
  );
}

export async function getStaticProps({ params }) {
  const city = cities.find((c) => c.slug === params.index);
  return {
    props: { city }
  };
}

export async function getStaticPaths() {
  const paths = cities.map((city) => ({
    params: { 
      index: city.slug,
    },
}))

  return {
    paths,
    fallback: false,
  };
}

const cities = [
  { name: "Ampuis", slug: "ampuis", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Anse", slug: "anse", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Albigny-sur-Saône", slug: "albigny-sur-saone", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Belleville", slug: "belleville", region: "Rhône", preName:"à", preDep:"le"},
  { name: "Bois-d'Oingt", slug: "bois-d-oingt", region: "Rhône", preName:"au", preDep:"le"},
  { name: "Brignais", slug: "brignais", region: "Rhône", preName:"à", preDep:"le"},
  { name: "Bron", slug: "bron", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Cailloux-sur-Fontaines", slug: "cailloux-sur-fontaines", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Caluire-et-Cuire", slug: "caluire-et-cuire", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Champagne-au-Mont-d'Or", slug: "champagne-au-mont-d-or", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Charbonnières-les-Bains", slug: "charbonnieres-les-bains", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Charly", slug: "charly", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Chasselay", slug: "chasselay", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Chassieu", slug: "chassieu", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Collonges-au-Mont-d'Or", slug: "collonges-au-mont-d-or", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Communay", slug: "communay", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Condrieu", slug: "condrieu", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Corbas", slug: "corbas", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Couzon-au-Mont-d'Or", slug: "couzon-au-mont-d-or", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Craponne", slug: "craponne", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Curis-au-Mont-d'Or", slug: "curis-au-mont-d-or", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Dardilly", slug: "dardilly", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Décines-Charpieu", slug: "decines-charpieu", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Écully", slug: "ecully", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Feyzin", slug: "feyzin", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Fleurieu-sur-Saône", slug: "fleurieu-sur-saone", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Fontaines-Saint-Martin", slug: "fontaines-saint-martin", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Fontaines-sur-Saône", slug: "fontaines-sur-saone", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Francheville", slug: "francheville", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Genas", slug: "genas", region: "Rhône", preName:"à", preDep:"le"},
  { name: "Genay", slug: "genay", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Givors", slug: "givors", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Gleizé", slug: "gleize", region: "Rhône", preName:"à", preDep:"le"},
  { name: "Grigny", slug: "grigny", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Irigny", slug: "irigny", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Jonage", slug: "jonage", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Jons", slug: "jons", region: "Rhône", preName:"à", preDep:"le" },
  { name: "L'Arbresle", slug: "l-arbresle", region: "Rhône", preName:"à", preDep:"le"},
  { name: "La Tour-de-Salvagny", slug: "la-tour-de-salvagny", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Limonest", slug: "limonest", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Lissieu", slug: "lissieu", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Loire-sur-Rhône", slug: "loire-sur-rhone", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Lyon", slug: "lyon", region: "Rhône", preName:"à", preDep:"le"},
  { name: "Lyon 1 er", slug: "lyon-69001", region: "Rhône", preName:"à", preDep:"le"},
  { name: "Lyon 2 ème", slug: "lyon-69002", region: "Rhône", preName:"à", preDep:"le"},
  { name: "Lyon 3 ème", slug: "lyon-69003", region: "Rhône", preName:"à", preDep:"le"},
  { name: "Lyon 4 ème", slug: "lyon-69004", region: "Rhône", preName:"à", preDep:"le"},
  { name: "Lyon 5 ème", slug: "lyon-69005", region: "Rhône", preName:"à", preDep:"le"},
  { name: "Lyon 6 ème", slug: "lyon-69006", region: "Rhône", preName:"à", preDep:"le"},
  { name: "Lyon 7 ème", slug: "lyon-69007", region: "Rhône", preName:"à", preDep:"le"},
  { name: "Lyon 8 ème", slug: "lyon-69008", region: "Rhône", preName:"à", preDep:"le"},
  { name: "Lyon 9 ème", slug: "lyon-69009", region: "Rhône", preName:"à", preDep:"le"},
  { name: "Marcy-l'Étoile", slug: "marcy-l-etoile", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Meyzieu", slug: "meyzieu", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Mions", slug: "mions", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Montanay", slug: "montanay", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Mornant", slug: "mornant", region: "Rhône", preName:"à", preDep:"le"},
  { name: "Neuville-sur-Saône", slug: "neuville-sur-saone", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Oullins", slug: "oullins", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Pierre-Bénite", slug: "pierre-benite", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Poleymieux-au-Mont-d'Or", slug: "poleymieux-au-mont-d-or", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Quincieux", slug: "quincieux", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Rillieux-la-Pape", slug: "rillieux-la-pape", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Rochetaillée-sur-Saône", slug: "rochetaillee-sur-saone", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Saint-Cyr-au-Mont-d'Or", slug: "saint-cyr-au-mont-d-or", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Saint-Cyr-sur-le-Rhône", slug: "saint-cyr-sur-le-rhone", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Saint-Didier-au-Mont-d'Or", slug: "saint-didier-au-mont-d-or", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Sainte-Colombe", slug: "sainte-colombe", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Sainte-Foy-lès-Lyon", slug: "sainte-foy-les-lyon", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Saint-Genis-Laval", slug: "saint-genis-laval", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Saint-Genis-les-Ollières", slug: "saint-genis-les-ollières", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Saint-Germain-au-Mont-d'Or", slug: "saint-germain-au-mont-d-or", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Saint-Romain-au-Mont-d'Or", slug: "saint-romain-au-mont-d-or", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Saint-Romain-en-Gal", slug: "saint-romain-en-gal", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Saint-Symphorien-d'Ozon", slug: "saint-symphorien-d-ozon", region: "Rhône", preName:"à", preDep:"le"},
  { name: "Sathonay-Camp", slug: "sathonay-camp", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Sathonay-Village", slug: "sathonay-village", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Sérézin-du-Rhône", slug: "serezin-du-rhone", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Solaize", slug: "solaize", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Tarare", slug: "tarare", region: "Rhône", preName:"à", preDep:"le"},
  { name: "Tassin-la-Demi-Lune", slug: "tassin-la-demi-lune", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Ternay", slug: "ternay", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Thizy-les-Bourgs", slug: "thizy-les-bourgs", region: "Rhône", preName:"à", preDep:"le"},
  { name: "Tupin-et-Semons", slug: "tupin-et-semons", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Vaugneray", slug: "vaugneray", region: "Rhône", preName:"à", preDep:"le"},
  { name: "Vernaison", slug: "vernaison", region: "Rhône", preName:"à", preDep:"le" },
  { name: "Villefranche-sur-Saône", slug: "villefranche-sur-Saone", region: "Rhône", preName:"à", preDep:"le"},


  { name: "Ambérieu-en-Bugey", slug: "amberieu-en-bugey", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Anglefort", slug: "anglefort", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Attignat", slug: "attignat", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Balan", slug: "balan", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Bellegarde-sur-Valserine", slug: "bellegarde-sur-valserine", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Belley", slug: "belley", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Beynost", slug: "beynost", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Billiat", slug: "billiat", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Bourg-en-Bresse", slug: "bourg-en-bresse", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Brégnier-Cordon", slug: "bregnier-cordon", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Brens", slug: "brens", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Briord", slug: "briord", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Ceyzériat", slug: "ceyzeriat", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Challex", slug: "challex", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Chanay", slug: "chanay", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Châtillon-sur-Chalaronne", slug: "chatillon-sur-chalaronne", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Collonges", slug: "collonges", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Corbonod", slug: "corbonod", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Cressin-Rochefort", slug: "cressin-rochefort", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Culoz", slug: "culoz", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Gex", slug: "gex", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Groslée-Saint-Benoit", slug: "groslee-saint-benoit", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Injoux-Génissiat", slug: "injoux-genissiat", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Hauteville-Lompnes", slug: "hauteville-lompnes", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Lagnieu", slug: "lagnieu", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Lavours", slug: "lavours", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Léaz", slug: "leaz", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Lhuis", slug: "lhuis", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Loyettes", slug: "loyettes", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Massignieu-de-Rives", slug: "massignieu-de-rives", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Meximieux", slug: "meximieux", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Miribel", slug: "miribel", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Montagnieu", slug: "montagnieu", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Murs-et-Gélignieux", slug: "murs-et-gelignieux", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Nantua", slug: "nantua", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Neyron", slug: "neyron", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Niévroz", slug: "nievroz", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Oyonnax", slug: "oyonnax", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Parves et Nattages", slug: "parves-et-nattages", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Peyrieu", slug: "peyrieu", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Pont-d'Ain", slug: "pont-d-ain", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Pougny", slug: "pougny", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Replonges", slug: "replonges", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Saint-Étienne-du-Bois", slug: "saint-etienne-du-bois", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Saint-Genis-Pouilly", slug: "saint-genis-pouilly", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Saint-Sorlin-en-Bugey", slug: "saint-sorlin-en-bugey", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Saint-Vulbas", slug: "saint-vulbas", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Saint-Maurice-de-Beynost", slug: "saint-maurice-de-beynost", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Saint-Maurice-de-Gourdans", slug: "saint-maurice-de-gourdans", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Sault-Brénaz", slug: "sault-brenaz", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Serrières-de-Briord", slug: "serrieres-de-briord", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Seyssel", slug: "seyssel", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Surjoux-Lhopital", slug: "surjoux-lhopital", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Thoiry", slug: "thoiry", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Thil", slug: "thil", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Trévoux", slug: "trevoux", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Valserhône", slug: "valserhône", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Villars-les-Dombes", slug: "villars-les-dombes", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Virignin", slug: "virignin", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Villebois", slug: "villebois", region: "Ain", preName:"à", preDep:"l'"},
  { name: "Vonnas", slug: "vonnas", region: "Ain", preName:"à", preDep:"l'"},
  
  
  { name: "Anthon", slug: "anthon", region: "Isère", preName:"à", preDep:"l'"},
  { name: "Aoste", slug: " aoste", region: "Isère", preName:"à", preDep:"l'"},
  { name: "Avenières", slug: "les-avenières", region: "Isère", preName:"aux", preDep:"l'"},
  { name: "Bièvre", slug: "bievre", region: "Isère", preName:"à", preDep:"l'"},
  { name: "Bouchage", slug: "le-bouchage", region: "Isère", preName:"au", preDep:"l'"},
  { name: "Bourgoin-Jallieu", slug: "bourgoin-jallieu", region: "Isère", preName:"à", preDep:"l'"},
  { name: "Bouvesse-Quirieu", slug: "bouvesse-quirieu", region: "Isère", preName:"à", preDep:"l'"},
  { name: "Brangues", slug: "brangues", region: "Isère", preName:"à", preDep:"l'"},
  { name: "Chartreuse-Guiers", slug: "chartreuse-guiers", region: "Isère", preName:"à", preDep:"l'"},
  { name: "Charvieu-Chavagneux", slug: "charvieu-chavagneux", region: "Isère", preName:"à", preDep:"l'"},
  { name: "Chasse-sur-Rhône", slug: "chasse-sur-rhone", region: "Isère", preName:"à", preDep:"l'"},
  { name: "Chavanoz", slug: "chavanoz", region: "Isère", preName:"à", preDep:"l'"},
  { name: "Chonas-l'Amballan", slug: "chonas-l-amballan", region: "Isère", preName:"à", preDep:"l'"},
  { name: "Creys-Mépieu", slug: "creys-mepieu", region: "Isère", preName:"à", preDep:"l'"},
  { name: "Échirolles", slug: "echirolles", region: "Isère", preName:"à", preDep:"l'"},
  { name: "Fontaine-Seyssinet", slug: "fontaine-seyssinet", region: "Isère", preName:"à", preDep:"l'"},
  { name: "Fontaine-Vercors", slug: "fontaine-vercors", region: "Isère", preName:"à", preDep:"l'"},
  { name: "Grésivaudan", slug: "gresivaudan", region: "Isère", preName:"au", preDep:"l'"},
  { name: "Hières-sur-Amby", slug: "hieres-sur-amby", region: "Isère", preName:"à", preDep:"l'"},
  { name: "La Balme-les-Grottes", slug: "la-balme-les-grottes", region: "Isère", preName:"à", preDep:"l'"},
  { name: "La Verpillière", slug: "la-verpilliere", region: "Isère", preName:"à", preDep:"l'"},
  { name: "La Tour-du-Pin", slug: "la-tour-du-pin", region: "Isère", preName:"à", preDep:"l'"},
  { name: "L'Isle-d'Abeau", slug: "l-isle-d-abeau", region: "Isère", preName:"à", preDep:"l'"},
  { name: "Grand-Lemps", slug: "le-grand-lemps", region: "Isère", preName:"au", preDep:"l'"},
  { name: "Pont-de-Claix", slug: "pont-de-claix", region: "Isère", preName:"au", preDep:"l'"},
  { name: "Grenoble", slug: "grenoble", region: "Isère", preName:"à", preDep:"l'"},
  { name: "Matheysine-Trièves", slug: "matheysine-trieves", region: "Isère", preName:"à", preDep:"l'"},
  { name: "Meylan", slug: "meylan", region: "Isère", preName:"à", preDep:"l'"},
  { name: "Montalieu-Vercieu", slug: "montalieu-vercieu", region: "Isère", preName:"à", preDep:"l'"},
  { name: "Morestel", slug: "morestel", region: "Isère", preName:"à", preDep:"l'"},
  { name: "Oisans-Romanche", slug: "oisans-romanche", region: "Isère", preName:"à", preDep:"l'"},
  { name: "Péage-de-Roussillon", slug: "peage-de-roussillon", region: "Isère", preName:"à", preDep:"l'"},
  { name: "Porcieu-Amblagnieu", slug: "porcieu-amblagnieu", region: "Isère", preName:"à", preDep:"l'"},
  { name: "Reventin-Vaugris", slug: "reventin-vaugris", region: "Isère", preName:"à", preDep:"l'"},
  { name: "Roches-de-Condrieu", slug: "voiron", region: "Isère", preName:"aux", preDep:"l'"},
  { name: "Roussillon", slug: "roussillon", region: "Isère", preName:"à", preDep:"l'"},
  { name: "Sablons", slug: "sablons", region: "Isère", preName:"à", preDep:"l'"},
  { name: "Saint-Alban-du-Rhône", slug: "saint-alban-du-rhone", region: "Isère", preName:"à", preDep:"l'"},
  { name: "Saint-Clair-du-Rhône", slug: "saint-clair-du-rhone", region: "Isère", preName:"à", preDep:"l'"},
  { name: "Saint-Martin-d'Hères", slug: "saint-martin-d-heres", region: "Isère", preName:"à", preDep:"l'"},
  { name: "Saint-Maurice-l'Exil", slug: "saint-maurice-l-exil", region: "Isère", preName:"à", preDep:"l'"},
  { name: "Saint-Prim", slug: "saint-prim", region: "Isère", preName:"à", preDep:"l'"},
  { name: "Saint-Romain-de-Jalionas", slug: "saint-romain-de-jalionas", region: "Isère", preName:"à", preDep:"l'"},
  { name: "Saint-Victor-de-Morestel", slug: "saint-victor-de-morestel", region: "Isère", preName:"à", preDep:"l'"},
  { name: "Salaise-sur-Sanne", slug: "salaise-sur-sanne", region: "Isère", preName:"à", preDep:"l'"},
  { name: "Seyssuel", slug: "seyssuel", region: "Isère", preName:"à", preDep:"l'"},
  { name: "Tullins", slug: "tullins", region: "Isère", preName:"à", preDep:"l'"},
  { name: "Vertrieu", slug: "vertrieu", region: "Isère", preName:"à", preDep:"l'"},
  { name: "Veyrins-Thuellin", slug: "veyrins-thuellin", region: "Isère", preName:"à", preDep:"l'"},
  { name: "Vienne", slug: "vienne", region: "Isère", preName:"à", preDep:"l'"},
  { name: "Villette-d'Anthon", slug: "villette-d-anthon", region: "Isère", preName:"à", preDep:"l'"},
  { name: "Voiron", slug: "voiron", region: "Isère", preName:"à", preDep:"l'"},


  { name: "Ancône", slug: "ancone", region: "Drôme", preName:"à", preDep:"la"},
  { name: "Andancette", slug: "andancette", region: "Drôme", preName:"à", preDep:"la"},
  { name: "Bourg-de-Péage", slug: "bourg-de-peage", region: "Drôme", preName:"à", preDep:"la"},
  { name: "Bourg-lès-Valence", slug: "bourg-les-valence", region: "Drôme", preName:"à", preDep:"la"},
  { name: "Châteauneuf-du-Rhône", slug: "chateauneuf-du-rhone", region: "Drôme", preName:"à", preDep:"la"},
  { name: "Châtillon-en-Diois", slug: "chatillon-en-diois", region: "Drôme", preName:"à", preDep:"la"},
  { name: "Chatuzange-le-Goubet", slug: "chatuzange-le-goubet", region: "Drôme", preName:"à", preDep:"la"},
  { name: "Crest", slug: "crest", region: "Drôme", preName:"à", preDep:"la"},
  { name: "Crozes-Hermitage", slug: "crozes-hermitage", region: "Drôme", preName:"à", preDep:"la"},
  { name: "Dieulefit", slug: "dieulefit", region: "Drôme", preName:"à", preDep:"la"},
  { name: "Donzère", slug: "donzere", region: "Drôme", preName:"à", preDep:"la"},
  { name: "Érôme", slug: "erome", region: "Drôme", preName:"à", preDep:"la"},
  { name: "Étoile-sur-Rhône", slug: "etoile-sur-rhone", region: "Drôme", preName:"à", preDep:"la"},
  { name: "Gervans", slug: "gervans", region: "Drôme", preName:"à", preDep:"la"},
  { name: "Grignan", slug: "grignan", region: "Drôme", preName:"à", preDep:"la"},
  { name: "La Coucourde", slug: "la-coucourde", region: "Drôme", preName:"à", preDep:"la"},
  { name: "La Roche-de-Glun", slug: "la-roche-de-glun", region: "Drôme", preName:"à", preDep:"la"},
  { name: "Laveyron", slug: "laveyron", region: "Drôme", preName:"à", preDep:"la"},
  { name: "Les Tourrettes", slug: "les-tourrettes", region: "Drôme", preName:"à", preDep:"la"},
  { name: "Livron-sur-Drôme", slug: "livron-sur-drome", region: "Drôme", preName:"à", preDep:"la"},
  { name: "Loriol-sur-Drôme", slug: "loriol-sur-drome", region: "Drôme", preName:"à", preDep:"la"},
  { name: "Mercurol-Veaunes", slug: "mercurol-veaunes", region: "Drôme", preName:"à", preDep:"la"},
  { name: "Montélimar", slug: "montelimar", region: "Drôme", preName:"à", preDep:"la"},
  { name: "Nyons", slug: "nyons", region: "Drôme", preName:"à", preDep:"la"},
  { name: "Ponsas", slug: "ponsas", region: "Drôme", preName:"à", preDep:"la"},
  { name: "Portes-lès-Valence", slug: "portes-les-valence", region: "Drôme", preName:"à", preDep:"la"},
  { name: "Pierrelatte", slug: "pierrelatte", region: "Drôme", preName:"à", preDep:"la"},
  { name: "Romans-sur-Isère", slug: "romans-sur-isere", region: "Drôme", preName:"à", preDep:"la"},
  { name: "Saint-Donat-sur-l'Herbasse", slug: "saint-donat-sur-l-herbasse", region: "Drôme", preName:"à", preDep:"la"},
  { name: "Saint-Rambert-d'Albon", slug: "saint-rambert-d-albon", region: "Drôme", preName:"à", preDep:"la"},
  { name: "Saint-Vallier", slug: "saint-vallier", region: "Drôme", preName:"à", preDep:"la"},
  { name: "Saulce-sur-Rhône", slug: "saulce-sur-rhone", region: "Drôme", preName:"à", preDep:"la"},
  { name: "Savasse", slug: "savasse", region: "Drôme", preName:"à", preDep:"la"},
  { name: "Serves-sur-Rhône", slug: "serves-sur-rhone", region: "Drôme", preName:"à", preDep:"la"},
  { name: "Tain-l'Hermitage", slug: "tain-l-hermitage", region: "Drôme", preName:"à", preDep:"la"},
  { name: "Tricastin", slug: "tricastin", region: "Drôme", preName:"au", preDep:"la"},
  { name: "Valence", slug: "valence", region: "Drôme", preName:"à", preDep:"la"},


  { name: "Annonay", slug: "annonay", region: "Ardèche", preName:"à", preDep:"l'"},
  { name: "Arras-sur-Rhône", slug: "arras-sur-rhone", region: "Ardèche", preName:"à", preDep:"l'"},
  { name: "Aubenas", slug: "aubenas", region: "Ardèche", preName:"à", preDep:"l'"},
  { name: "Baix", slug: "baix", region: "Ardèche", preName:"à", preDep:"l'"},
  { name: "Beauchastel", slug: "beauchastel", region: "Ardèche", preName:"à", preDep:"l'"},
  { name: "Berg-Helvie", slug: "berg-helvie", region: "Ardèche", preName:"à", preDep:"l'"},
  { name: "Bourg-Saint-Andéol", slug: "bourg-saint-andeol", region: "Ardèche", preName:"à", preDep:"l'"},
  { name: "Champagne", slug: "champagne", region: "Ardèche", preName:"à", preDep:"l'"},
  { name: "Charmes-sur-Rhône", slug: "charmes-sur-rhone", region: "Ardèche", preName:"à", preDep:"l'"},
  { name: "Châteaubourg", slug: "chateaubourg", region: "Ardèche", preName:"à", preDep:"l'"},
  { name: "Cornas", slug: "cornas", region: "Ardèche", preName:"à", preDep:"l'"},
  { name: "Cruas", slug: "cruas", region: "Ardèche", preName:"à", preDep:"l'"},
  { name: "Glun", slug: "glun", region: "Ardèche", preName:"à", preDep:"l'"},
  { name: "Guilherand-Granges", slug: "guilherand-granges", region: "Ardèche", preName:"à", preDep:"l'"},
  { name: "Haut-Eyrieux", slug: "haut-eyrieux", region: "Ardèche", preName:"à", preDep:"l'"},
  { name: "Lamastre", slug: "lamastre", region: "Ardèche", preName:"à", preDep:"l'"},
  { name: "Thueyts", slug: "thueyts", region: "Ardèche", preName:"à", preDep:"l'"},
  { name: "La Voulte-sur-Rhône", slug: "la-voulte-sur-rhone", region: "Ardèche", preName:"à", preDep:"l'"},
  { name: "Largentière", slug: "largentiere", region: "Ardèche", preName:"à", preDep:"l'"},
  { name: "Le Cheylard", slug: "le-cheylard", region: "Ardèche", preName:"à", preDep:"l'"},
  { name: "Lemps", slug: "lemps", region: "Ardèche", preName:"à", preDep:"l'"},
  { name: "Le Pouzin", slug: "le-pouzin", region: "Ardèche", preName:"à", preDep:"l'"},
  { name: "Le Teil", slug: "le-teil", region: "Ardèche", preName:"à", preDep:"l'"},
  { name: "Les Vans", slug: "les-vans", region: "Ardèche", preName:"à", preDep:"l'"},
  { name: "Limony", slug: "limony", region: "Ardèche", preName:"à", preDep:"l'"},
  { name: "Mauves", slug: "mauves", region: "Ardèche", preName:"à", preDep:"l'"},
  { name: "Meysse", slug: "meysse", region: "Ardèche", preName:"à", preDep:"l'"},
  { name: "Ozon", slug: "ozon", region: "Ardèche", preName:"à", preDep:"l'"},
  { name: "Peyraud", slug: "peyraud", region: "Ardèche", preName:"à", preDep:"l'"},
  { name: "Privas", slug: "privas", region: "Ardèche", preName:"à", preDep:"l'"},
  { name: "Rochemaure", slug: "rochemaure", region: "Ardèche", preName:"à", preDep:"l'"},
  { name: "Rompon", slug: "rompon", region: "Ardèche", preName:"à", preDep:"l'"},
  { name: "Saint-Désirat", slug: "saint-desirat", region: "Ardèche", preName:"à", preDep:"l'"},
  { name: "Saint-Georges-les-Bains", slug: "saint-georges-les-bains", region: "Ardèche", preName:"à", preDep:"l'"},
  { name: "Saint-Jean-de-Muzols", slug: "saint-jean-de-muzols", region: "Ardèche", preName:"à", preDep:"l'"},
  { name: "Saint-Just-d'Ardèche", slug: "saint-just-d-ardeche", region: "Ardèche", preName:"à", preDep:"l'"},
  { name: "Saint-Marcel-d'Ardèche", slug: "saint-marcel-d-ardeche", region: "Ardèche", preName:"à", preDep:"l'"},
  { name: "Saint-Montan", slug: "saint-montan", region: "Ardèche", preName:"à", preDep:"l'"},
  { name: "Saint-Péray", slug: "saint-peray", region: "Ardèche", preName:"à", preDep:"l'"},
  { name: "Sarras", slug: "sarras", region: "Ardèche", preName:"à", preDep:"l'"},
  { name: "Serrières", slug: "serrieres", region: "Ardèche", preName:"à", preDep:"l'"},
  { name: "Soyons", slug: "soyons", region: "Ardèche", preName:"à", preDep:"l'"},
  { name: "Thueyts", slug: "thueyts", region: "Ardèche", preName:"à", preDep:"l'"},
  { name: "Tournon-sur-Rhône", slug: "tournon-sur-rhone", region: "Ardèche", preName:"à", preDep:"l'"},
  { name: "Vallon-Pont-d'Arc", slug: "vallon-pont-d-arc", region: "Ardèche", preName:"à", preDep:"l'"},
  { name: "Vion", slug: "vion", region: "Ardèche", preName:"à", preDep:"l'"},
  { name: "Viviers", slug: "viviers", region: "Ardèche", preName:"à", preDep:"l'"},
  

  { name: "Aix-les-Bains", slug: "aix-les-bains", region: "Savoie", preName:"à", preDep:"la"},
  { name: "Albertville", slug: "albertville", region: "Savoie", preName:"à", preDep:"la"},
  { name: "Bourg-Saint-Maurice", slug: "bourg-saint-maurice", region: "Savoie", preName:"à", preDep:"la"},
  { name: "Chambéry", slug: "chambéry", region: "Savoie", preName:"à", preDep:"la"},
  { name: "Champagneux", slug: "champagneux", region: "Savoie", preName:"à", preDep:"la"},
  { name: "Chanaz", slug: "chanaz", region: "Savoie", preName:"à", preDep:"la"},
  { name: "Jongieux", slug: "jongieux", region: "Savoie", preName:"à", preDep:"la"},
  { name: "La Balme", slug: "la-balme", region: "Savoie", preName:"à", preDep:"la"},
  { name: "La Motte-Servolex", slug: "la-motte-servolex", region: "Savoie", preName:"à", preDep:"la"},
  { name: "La Ravoire", slug: "la-ravoire", region: "Savoie", preName:"à", preDep:"la"},
  { name: "Lucey", slug: "lucey", region: "Savoie", preName:"à", preDep:"la"},
  { name: "Pont-de-Beauvoisin", slug: "le-pont-de-beauvoisin", region: "Savoie", preName:"au", preDep:"la"},
  { name: "Modane", slug: "modane", region: "Savoie", preName:"à", preDep:"la"},
  { name: "Montmélian", slug: "montmelian", region: "Savoie", preName:"à", preDep:"la"},
  { name: "Motz", slug: "motz", region: "Savoie", preName:"à", preDep:"la"},
  { name: "Moûtiers", slug: "moutiers", region: "Savoie", preName:"à", preDep:"la"},
  { name: "Ruffieux", slug: "ruffieux", region: "Savoie", preName:"à", preDep:"la"},
  { name: "Saint-Alban-Leysse", slug: "saint-alban-leysse", region: "Savoie", preName:"à", preDep:"la"},
  { name: "Saint-Genix-les-Villages", slug: "saint-genix-les-villages", region: "Savoie", preName:"à", preDep:"la"},
  { name: "Saint-Jean-de-Maurienne", slug: "saint-jean-de-maurienne", region: "Savoie", preName:"à", preDep:"la"},
  { name: "Saint-Pierre-d'Albigny", slug: "saint-pierre-d-albigny", region: "Savoie", preName:"à", preDep:"la"},
  { name: "Serrières-en-Chautagne", slug: "serrieres-en-chautagne", region: "Savoie", preName:"à", preDep:"la"},
  { name: "Ugine", slug: "ugine", region: "Savoie", preName:"à", preDep:"la"},
  { name: "Vions", slug: "vions", region: "Savoie", preName:"à", preDep:"la"},
  { name: "Yenne", slug: "yenne", region: "Savoie", preName:"à", preDep:"la"},


  { name: "Annecy", slug: "annecy", region: "Haute-Savoie", preName:"à", preDep:"la"},
  { name: "Annemasse", slug: "annemasse", region: "Haute-Savoie", preName:"à", preDep:"la"},
  { name: "Anthy-sur-Léman", slug: "anthy-sur-leman", region: "Haute-Savoie", preName:"à", preDep:"la"},
  { name: "Bassy", slug: "bassy", region: "Haute-Savoie", preName:"à", preDep:"la"},
  { name: "Bonneville", slug: "bonneville", region: "Haute-Savoie", preName:"à", preDep:"la"},
  { name: "Challonges", slug: "challonges", region: "Haute-Savoie", preName:"à", preDep:"la"},
  { name: "Chens-sur-Léman", slug: "chens-sur-leman", region: "Haute-Savoie", preName:"à", preDep:"la"},
  { name: "Chevrier", slug: "chevrier", region: "Haute-Savoie", preName:"à", preDep:"la"},
  { name: "Clarafond-Arcine", slug: "clarafond-arcine", region: "Haute-Savoie", preName:"à", preDep:"la"},
  { name: "Collonges-sous-Salève", slug: "collonges-sous-saleve", region: "Haute-Savoie", preName:"à", preDep:"la"},
  { name: "Cluses", slug: "cluses", region: "Haute-Savoie", preName:"à", preDep:"la"},
  { name: "Éloise", slug: "eloise", region: "Haute-Savoie", preName:"à", preDep:"la"},
  { name: "Evian-les-bains", slug: "evian-les-bains", region: "Haute-Savoie", preName:"à", preDep:"la"},
  { name: "Excenevex", slug: "excenevex", region: "Haute-Savoie", preName:"à", preDep:"la"},
  { name: "Faverges-Seythenex", slug: "faverges-seythenex", region: "Haute-Savoie", preName:"à", preDep:"la"},
  { name: "Franclens", slug: "franclens", region: "Haute-Savoie", preName:"à", preDep:"la"},
  { name: "Gaillard", slug: "gaillard", region: "Haute-Savoie", preName:"à", preDep:"la"},
  { name: "Chamonix", slug: "chamonix", region: "Haute-Savoie", preName:"à", preDep:"la"},
  { name: "La Roche-sur-foron", slug: "la-roche-sur-foron", region: "Haute-Savoie", preName:"à", preDep:"la"},
  { name: "Lugrin", slug: "lugrin", region: "Haute-Savoie", preName:"à", preDep:"la"},
  { name: "Margencel", slug: "margencel", region: "Haute-Savoie", preName:"à", preDep:"la"},
  { name: "Maxilly-sur-Léman", slug: "maxilly-sur-leman", region: "Haute-Savoie", preName:"à", preDep:"la"},
  { name: "Meillerie", slug: "meillerie", region: "Haute-Savoie", preName:"à", preDep:"la"},
  { name: "Messery", slug: "messery", region: "Haute-Savoie", preName:"à", preDep:"la"},
  { name: "Nernier", slug: "nernier", region: "Haute-Savoie", preName:"à", preDep:"la"},
  { name: "Neuvecelle", slug: "neuvecelle", region: "Haute-Savoie", preName:"à", preDep:"la"},
  { name: "Publier", slug: "publier", region: "Haute-Savoie", preName:"à", preDep:"la"},
  { name: "Rumilly", slug: "rumilly", region: "Haute-Savoie", preName:"à", preDep:"la"},
  { name: "Saint-Germain-sur-Rhône", slug: "saint-germain-sur-rhone", region: "Haute-Savoie", preName:"à", preDep:"la"},
  { name: "Saint-Gingolph", slug: "saint-gingolph", region: "Haute-Savoie", preName:"à", preDep:"la"},
  { name: "Saint-Julien-en-Genevois", slug: "saint-julien-en-Genevois", region: "Haute-Savoie", preName:"à", preDep:"la"},
  { name: "Sallanches", slug: "sallanches", region: "Haute-Savoie", preName:"à", preDep:"la"},
  { name: "Sciez", slug: "sciez", region: "Haute-Savoie", preName:"à", preDep:"la"},
  { name: "Seynod", slug: "seynod", region: "Haute-Savoie", preName:"à", preDep:"la"},
  { name: "Seyssel", slug: "seyssel", region: "Haute-Savoie", preName:"à", preDep:"la"},
  { name: "Thonon-les-Bains", slug: "thonon-les-Bains", region: "Haute-Savoie", preName:"à", preDep:"la"},
  { name: "Viry", slug: "viry", region: "Haute-Savoie", preName:"à", preDep:"la"},
  { name: "Vulbens", slug: "vulbens", region: "Haute-Savoie", preName:"à", preDep:"la"},
  { name: "Yvoire", slug: "yvoire", region: "Haute-Savoie", preName:"à", preDep:"la"},


  { name: "Andrézieux-Bouthéon", slug: "andrezieux-boutheon", region: "Loire", preName:"à", preDep:"la"},
  { name: "Boën-sur-Lignon", slug: "boen-sur-lignon", region: "Loire", preName:"à", preDep:"la"},
  { name: "Chambles", slug: "chambles", region: "Loire", preName:"à", preDep:"la"},
  { name: "Charlieu", slug: "charlieu", region: "Loire", preName:"à", preDep:"la"},
  { name: "Chavanay", slug: "chavanay", region: "Loire", preName:"à", preDep:"la"},
  { name: "Feurs", slug: "feurs", region: "Loire", preName:"à", preDep:"la"},
  { name: "Firminy", slug: "firminy", region: "Loire", preName:"à", preDep:"la"},
  { name: "La Ricamarie", slug: "la-ricamarie", region: "Loire", preName:"à", preDep:"la"},
  { name: "La Talaudière", slug: "la-talaudiere", region: "Loire", preName:"à", preDep:"la"},
  { name: "Le Bessat", slug: "le-bessat", region: "Loire", preName:"à", preDep:"la"},
  { name: "Le Coteau", slug: "le-coteau", region: "Loire", preName:"à", preDep:"la"},
  { name: "Montbrison", slug: "montbrison", region: "Loire", preName:"à", preDep:"la"},
  { name: "Planfoy", slug: "planfoy", region: "Loire", preName:"à", preDep:"la"},
  { name: "Renaison", slug: "renaison", region: "Loire", preName:"à", preDep:"la"},
  { name: "Rive-de-Gier", slug: "rive-de-gier", region: "Loire", preName:"à", preDep:"la"},
  { name: "Roanne", slug: "roanne", region: "Loire", preName:"à", preDep:"la"},
  { name: "Roche-la-Molière", slug: "roche-la-moliere", region: "Loire", preName:"à", preDep:"la"},
  { name: "Saint-Chamond", slug: "saint-chamond", region: "Loire", preName:"à", preDep:"la"},
  { name: "Saint-Etienne", slug: "saint-etienne", region: "Loire", preName:"à", preDep:"la"},
  { name: "Saint-Genest-Lerp", slug: "saint-genest-lerp", region: "Loire", preName:"à", preDep:"la"},
  { name: "Saint-Genest-Malifaux", slug: "saint-genest-malifaux", region: "Loire", preName:"à", preDep:"la"},
  { name: "Saint-Jean-Bonnefonds", slug: "saint-jean-bonnefonds", region: "Loire", preName:"à", preDep:"la"},
  { name: "Saint-Just-Saint-Rambert", slug: "saint-just-saint-rambert", region: "Loire", preName:"à", preDep:"la"},
  { name: "Saint-Michel-sur-Rhône", slug: "saint-michel-sur-rhone", region: "Loire", preName:"à", preDep:"la"},
  { name: "Saint-Pierre-de-Boeuf", slug: "saint-pierre-de-boeuf", region: "Loire", preName:"à", preDep:"la"},
  { name: "Saint-Priest-en-Jarez", slug: "saint-priest-en-jarez", region: "Loire", preName:"à", preDep:"la"},
  { name: "Saint-Romain-les-Atheux", slug: "saint-romain-les-atheux", region: "Loire", preName:"à", preDep:"la"},
  { name: "Tarentaise", slug: "tarentaise", region: "Loire", preName:"à la", preDep:"la"},
  { name: "Sorbiers", slug: "sorbiers", region: "Loire", preName:"à", preDep:"la"},
  { name: "Veauche", slug: "veauche", region: "Loire", preName:"à", preDep:"la"},
  { name: "Vérin", slug: "verin", region: "Loire", preName:"à", preDep:"la"},
  { name: "Villars", slug: "villars", region: "Loire", preName:"à", preDep:"la"},


  { name: "Aurec-sur-Loire", slug: "aurec-sur-loire", region: "Haute-Loire", preName:"à", preDep:"la"},
  { name: "Bas-en-Basset", slug: "bas-en-basset", region: "Haute-Loire", preName:"à", preDep:"la"},
  { name: "Boutières", slug: "boutieres", region: "Haute-Loire", preName:"à", preDep:"la"},
  { name: "Brioude", slug: "brioude", region: "Haute-Loire", preName:"à", preDep:"la"},
  { name: "Emblavez-et-Meygal", slug: "emblavez-et-meygal", region: "Haute-Loire", preName:"à", preDep:"la"},
  { name: "Langeac", slug: "langeac", region: "Haute-Loire", preName:"à", preDep:"la"},
  { name: "Puy-en-Velay", slug: "puy-en-velay", region: "Haute-Loire", preName:"au", preDep:"la"},
  { name: "Sainte-Sigolène", slug: "sainte-sigolene", region: "Haute-Loire", preName:"à", preDep:"la"},
  { name: "Mézenc", slug: "mezenc", region: "Haute-Loire", preName:"à", preDep:"la"},
  { name: "Monistrol-sur-Loire", slug: "monistrol-sur-loire", region: "Haute-Loire", preName:"à", preDep:"la"},
  { name: "Mazeyrat-d'Allier", slug: "mazeyrat-d-allier", region: "Haute-Loire", preName:"à", preDep:"la"},
  { name: "Craponne-sur-Arzon", slug: "craponne-sur-arzon", region: "Haute-Loire", preName:"à", preDep:"la"},
  { name: "Saint-Paulien", slug: "saint-paulien", region: "Haute-Loire", preName:"à", preDep:"la"},
  { name: "Sainte-Florine", slug: "sainte-florine", region: "Haute-Loire", preName:"à", preDep:"la"},
  { name: "Cussac-sur-Loire", slug: "cussac-sur-loire", region: "Haute-Loire", preName:"à", preDep:"la"},
  { name: "Yssingeaux", slug: "yssingeaux", region: "Haute-Loire", preName:"à", preDep:"la"},

  { name:"Autun", slug: "autun", region: "Saône-et-Loire", preName:"à", preDep:"la" },
  { name:"Blanzy", slug: "blanzy", region: "Saône-et-Loire", preName:"à", preDep:"la" },
  { name:"Bourbon-Lancy", slug: "bourbon-lancy", region: "Saône-et-Loire", preName:"à", preDep:"la" },
  { name:"Branges", slug: "branges", region: "Saône-et-Loire", preName:"à", preDep:"la" },
  { name:"Buxy", slug: "buxy", region: "Saône-et-Loire", preName:"à", preDep:"la" },
  { name:"Chagny", slug: "chagny", region: "Saône-et-Loire", preName:"à", preDep:"la" },
  { name:"Chalon-sur-Saône", slug: "chalon-sur-saone", region: "Saône-et-Loire", preName:"à", preDep:"la" },
  { name:"Champforgeuil", slug: "champforgeuil", region: "Saône-et-Loire", preName:"à", preDep:"la" },
  { name:"Charolles", slug: "charolles", region: "Saône-et-Loire", preName:"à", preDep:"la" },
  { name:"Charnay-lès-Mâcon", slug: "charnay-les-macon", region: "Saône-et-Loire", preName:"à", preDep:"la" },
  { name:"Châtenoy-le-Royal", slug: "chatenoy-le-royal", region: "Saône-et-Loire", preName:"à", preDep:"la" },
  { name:"Chauffailles", slug: "chauffailles", region: "Saône-et-Loire", preName:"à", preDep:"la" },
  { name:"Ciry-le-Noble", slug: "ciry-le-noble", region: "Saône-et-Loire", preName:"à", preDep:"la" },
  { name:"Cluny", slug: "cluny", region: "Saône-et-Loire", preName:"à", preDep:"la" },
  { name:"Crêches-sur-Saône", slug: "creches-sur-saone", region: "Saône-et-Loire", preName:"à", preDep:"la" },
  { name:"Crissey", slug: "crissey", region: "Saône-et-Loire", preName:"à", preDep:"la" },
  { name:"Cuiseaux", slug: "cuiseaux", region: "Saône-et-Loire", preName:"à", preDep:"la" },
  { name:"Digoin", slug: "digoin", region: "Saône-et-Loire", preName:"à", preDep:"la" },
  { name:"Épinac", slug: "epinac", region: "Saône-et-Loire", preName:"à", preDep:"la" },
  { name:"Gergy", slug: "gergy", region: "Saône-et-Loire", preName:"à", preDep:"la" },
  { name:"Givry", slug: "givry", region: "Saône-et-Loire", preName:"à", preDep:"la" },
  { name:"Gueugnon", slug: "gueugnon", region: "Saône-et-Loire", preName:"à", preDep:"la" },
  { name:"Hurigny", slug: "hurigny", region: "Saône-et-Loire", preName:"à", preDep:"la" },
  { name:"La Chapelle-de-Guinchay", slug: "la-chapelle-de-guinchay", region: "Saône-et-Loire", preName:"à", preDep:"la" },
  { name:"Breuil", slug: "le-breuil", region: "Saône-et-Loire", preName:"à", preDep:"la" },
  { name:"Creusot", slug: "le-creusot", region: "Saône-et-Loire", preName:"au", preDep:"la" },
  { name:"Louhans", slug: "louhans", region: "Saône-et-Loire", preName:"à", preDep:"la" },
  { name:"Lux", slug: "lux", region: "Saône-et-Loire", preName:"à", preDep:"la" },
  { name:"Mâcon", slug: "macon", region: "Saône-et-Loire", preName:"à", preDep:"la" },
  { name:"Montceau-les-Mines", slug: "montceau-les-mines", region: "Saône-et-Loire", preName:"à", preDep:"la" },
  { name:"Montchanin", slug: "montchanin", region: "Saône-et-Loire", preName:"à", preDep:"la" },
  { name:"Ouroux-sur-Saône", slug: "ouroux-sur-saone", region: "Saône-et-Loire", preName:"à", preDep:"la" },
  { name:"Paray-le-Monial", slug: "paray-le-monial", region: "Saône-et-Loire", preName:"à", preDep:"la" },
  { name:"Pierre-de-Bresse", slug: "pierre-de-bresse", region: "Saône-et-Loire", preName:"à", preDep:"la" },
  { name:"Romanèche-Thorins", slug: "romaneche-thorins", region: "Saône-et-Loire", preName:"à", preDep:"la" },
  { name:"Saint-Germain-du-Plain", slug: "saint-germain-du-plain", region: "Saône-et-Loire", preName:"à", preDep:"la" },
  { name:"Saint-Marcel", slug: "saint-marcel", region: "Saône-et-Loire", preName:"à", preDep:"la" },
  { name:"Saint-Rémy", slug: "saint-remy", region: "Saône-et-Loire", preName:"à", preDep:"la" },
  { name:"Saint-Vallier", slug: "saint-vallier", region: "Saône-et-Loire", preName:"à", preDep:"la" },
  { name:"Sancé", slug: "sance", region: "Saône-et-Loire", preName:"à", preDep:"la" },
  { name:"Sanvignes-les-Mines", slug: "sanvignes-les-mines", region: "Saône-et-Loire", preName:"à", preDep:"la" },
  { name:"Sennecey-le-Grand", slug: "sennecey-le-grand", region: "Saône-et-Loire", preName:"à", preDep:"la" },
  { name:"Sornay", slug: "sornay", region: "Saône-et-Loire", preName:"à", preDep:"la" },
  { name:"Torcy", slug: "torcy", region: "Saône-et-Loire", preName:"à", preDep:"la" },
  { name:"Tournus", slug: "tournus", region: "Saône-et-Loire", preName:"à", preDep:"la" },
  { name:"Varennes-le-Grand", slug: "varennes-le-grand", region: "Saône-et-Loire", preName:"à", preDep:"la" },


  { name:"Arbois", slug: "arbois", region: "Jura", preName:"à", preDep:"le" },
  { name:"Authume", slug: "authume", region: "Jura", preName:"à", preDep:"le" },
  { name:"Bletterans", slug: "bletterans", region: "Jura", preName:"à", preDep:"le" },
  { name:"Champagnole", slug: "champagnole", region: "Jura", preName:"à", preDep:"le" },
  { name:"Dole", slug: "dole", region: "Jura", preName:"à", preDep:"le" },
  { name:"Lons-le-Saunier", slug: "lons-le-saunier", region: "Jura", preName:"à", preDep:"le" },
  { name:"Moirans-en-Montagne", slug: "moirans-en-montagne", region: "Jura", preName:"à", preDep:"le" },
  { name:"Mont-sous-Vaudrey", slug: "mont-sous-vaudrey", region: "Jura", preName:"au", preDep:"le" },
  { name:"Morez", slug: "morez", region: "Jura", preName:"à", preDep:"le" },
  { name:"Poligny", slug: "poligny", region: "Jura", preName:"à", preDep:"le" },
  { name:"Mont-sous-Vaudrey", slug: "mont-sous-vaudrey", region: "Jura", preName:"à", preDep:"le" },
  { name:"Saint-Amour", slug: "saint-amour", region: "Jura", preName:"à", preDep:"le" },
  { name:"Saint-Claude", slug: "saint-claude", region: "Jura", preName:"à", preDep:"le" },
  { name:"Saint-Laurent-en-Grandvaux", slug: "saint-laurent-en-grandvaux", region: "Jura", preName:"à", preDep:"le" },
  { name:"Saint-Lupicin", slug: "saint-lupicin", region: "Jura", preName:"à", preDep:"le" },
  { name:"Tavaux", slug: "tavaux", region: "Jura", preName:"à", preDep:"le" },


  { name:"Audincourt", slug: "audincourt", region: "Doubs", preName:"à", preDep:"le" },
  { name:"Baume-les-Dames", slug: "baume-les-dames", region: "Doubs", preName:"à", preDep:"le" },
  { name:"Bavans", slug: "bavans", region: "Doubs", preName:"à", preDep:"le" },
  { name: "Besançon", slug: "besançon", region: "Doubs", preName:"à", preDep:"le" },
  { name:"Bethoncourt", slug: "bethoncourt", region: "Doubs", preName:"à", preDep:"le" },
  { name:"Frasne", slug: "frasne", region: "Doubs", preName:"à", preDep:"le" },
  { name:"Grand-Charmont", slug: "grand-charmont", region: "Doubs", preName:"à", preDep:"le" },
  { name:"Maîche", slug: "maîche", region: "Doubs", preName:"à", preDep:"le" },
  { name:"Mandeure", slug: "mandeure", region: "Doubs", preName:"à", preDep:"le" },
  { name:"Montbéliard", slug: "montbéliard", region: "Doubs", preName:"à", preDep:"le" },
  { name:"Morteau", slug: "morteau", region: "Doubs", preName:"à", preDep:"le" },
  { name:"Ornans", slug: "ornans", region: "Doubs", preName:"à", preDep:"le" },
  { name:"Pontarlier", slug: "pontarlier", region: "Doubs", preName:"à", preDep:"le" },
  { name:"Pont-de-Roide-Vermondans", slug: "pont-de-roide-vermondans", region: "Doubs", preName:"au", preDep:"le" },
  { name:"Saint-Vit", slug: "saint-vit", region: "Doubs", preName:"à", preDep:"le" },
  { name:"Seloncourt", slug: "seloncourt", region: "Doubs", preName:"à", preDep:"le" },
  { name:"Sochaux", slug: "sochaux", region: "Doubs", preName:"à", preDep:"le" },
  { name:"Valdahon", slug: "valdahon", region: "Doubs", preName:"à", preDep:"le" },
  { name:"Valentigney", slug: "valentigney", region: "Doubs", preName:"à", preDep:"le" },
  { name:"Villers-le-Lac", slug: "villers-le-Lac", region: "Doubs", preName:"à", preDep:"le" }, 
];