import React, { useState } from "react";
import Link from "next/link";
import {
  AnimatePresence,
  AnimateSharedLayout,
  motion,
} from "framer-motion";
import zoneStyles from "../styles/ZonesElement.module.css";

export default function ZoneRhoneAlpes() {
  return (
    <AnimateSharedLayout>
      <motion.ul className={zoneStyles.listDepartementsB} layout>
        {departements.map((departement, index) => (
          <Item departement={departement} key={index} />
        ))}
      </motion.ul>
    </AnimateSharedLayout>
  );
}

function Item({ departement }) {
  const [isOpen, setIsOpen] = useState(false);

  const toggleOpen = () => setIsOpen(!isOpen);
  return (
    <div className={zoneStyles.departementContainer}>
      <motion.li
        className={zoneStyles.listDepartements}
        layout
        onClick={toggleOpen}
      >
        <motion.div className={zoneStyles.layoutDepartement} layout>
          {departement.region} ({departement.numero})
        </motion.div>
        <motion.div layout />
        <AnimatePresence>
          {isOpen && (
            <motion.div
              className={zoneStyles.listCities}
              layout
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
            >
              {departement.city.map((city, index) => (
                <motion.p className={zoneStyles.city} key={index}>
                  <Link href={city.slug}>
                    <strong>{city.name}</strong>
                  </Link>
                </motion.p>
              ))}
            </motion.div>
          )}
        </AnimatePresence>
      </motion.li>
    </div>
  );
}

const departements = [
  {
    region: "Rhône",
    numero: "69",
    city: [
      { name: "Ampuis", slug: "ampuis" },
      { name: "Anse", slug: "anse" },
      { name: "Albigny-sur-Saône", slug: "albigny-sur-saone" },
      { name: "Belleville", slug: "belleville" },
      { name: "Bois-d'Oingt", slug: "bois-d-oingt" },
      { name: "Brignais", slug: "brignais" },
      { name: "Bron", slug: "bron" },
      { name: "Cailloux-sur-Fontaines", slug: "cailloux-sur-fontaines" },
      { name: "Caluire-et-Cuire", slug: "caluire-et-cuire" },
      { name: "Champagne-au-Mont-d'Or", slug: "champagne-au-mont-d-or" },
      { name: "Charbonnières-les-Bains", slug: "charbonnieres-les-bains" },
      { name: "Charly", slug: "charly" },
      { name: "Chasselay", slug: "chasselay" },
      { name: "Chassieu", slug: "chassieu" },
      { name: "Collonges-au-Mont-d'Or", slug: "collonges-au-mont-d-or" },
      { name: "Communay", slug: "communay" },
      { name: "Condrieu", slug: "condrieu" },
      { name: "Corbas", slug: "corbas" },
      { name: "Couzon-au-Mont-d'Or", slug: "couzon-au-mont-d-or" },
      { name: "Craponne", slug: "craponne" },
      { name: "Curis-au-Mont-d'Or", slug: "curis-au-mont-d-or" },
      { name: "Dardilly", slug: "dardilly" },
      { name: "Décines-Charpieu", slug: "decines-charpieu" },
      { name: "Écully", slug: "ecully" },
      { name: "Feyzin", slug: "feyzin" },
      { name: "Fleurieu-sur-Saône", slug: "fleurieu-sur-saone" },
      { name: "Fontaines-Saint-Martin", slug: "fontaines-saint-martin" },
      { name: "Fontaines-sur-Saône", slug: "fontaines-sur-saone" },
      { name: "Francheville", slug: "francheville" },
      { name: "Genas", slug: "genas" },
      { name: "Genay", slug: "genay" },
      { name: "Givors", slug: "givors" },
      { name: "Gleizé", slug: "gleize" },
      { name: "Grigny", slug: "grigny" },
      { name: "Irigny", slug: "irigny" },
      { name: "Jonage", slug: "jonage" },
      { name: "Jons", slug: "jons" },
      { name: "L'Arbresle", slug: "l-arbresle" },
      { name: "La Tour-de-Salvagny", slug: "la-tour-de-salvagny" },
      { name: "Limonest", slug: "limonest" },
      { name: "Lissieu", slug: "lissieu" },
      { name: "Loire-sur-Rhône", slug: "loire-sur-rhone" },
      { name: "Lyon", slug: "lyon" },
      { name: "Marcy-l'Étoile", slug: "marcy-l-etoile" },
      { name: "Meyzieu", slug: "meyzieu" },
      { name: "Mions", slug: "mions" },
      { name: "Montanay", slug: "montanay" },
      { name: "Mornant", slug: "mornant" },
      { name: "Neuville-sur-Saône", slug: "neuville-sur-saone" },
      { name: "Oullins", slug: "oullins" },
      { name: "Pierre-Bénite", slug: "pierre-benite" },
      { name: "Poleymieux-au-Mont-d'Or", slug: "poleymieux-au-mont-d-or" },
      { name: "Quincieux", slug: "quincieux" },
      { name: "Rillieux-la-Pape", slug: "rillieux-la-pape" },
      { name: "Rochetaillée-sur-Saône", slug: "rochetaillee-sur-saone" },
      { name: "Saint-Cyr-au-Mont-d'Or", slug: "saint-cyr-au-mont-d-or" },
      { name: "Saint-Cyr-sur-le-Rhône", slug: "saint-cyr-sur-le-rhone" },
      { name: "Saint-Didier-au-Mont-d'Or", slug: "saint-didier-au-mont-d-or" },
      { name: "Sainte-Colombe", slug: "sainte-colombe" },
      { name: "Sainte-Foy-lès-Lyon", slug: "sainte-foy-les-lyon" },
      { name: "Saint-Genis-Laval", slug: "saint-genis-laval" },
      { name: "Saint-Genis-les-Ollières", slug: "saint-genis-les-ollières" },
      {
        name: "Saint-Germain-au-Mont-d'Or",
        slug: "saint-germain-au-mont-d-or",
      },
      { name: "Saint-Romain-au-Mont-d'Or", slug: "saint-romain-au-mont-d-or" },
      { name: "Saint-Romain-en-Gal", slug: "saint-romain-en-gal" },
      { name: "Saint-Symphorien-d'Ozon", slug: "saint-symphorien-d-ozon" },
      { name: "Sathonay-Camp", slug: "sathonay-camp" },
      { name: "Sathonay-Village", slug: "sathonay-village" },
      { name: "Sérézin-du-Rhône", slug: "serezin-du-rhone" },
      { name: "Solaize", slug: "solaize" },
      { name: "Tarare", slug: "tarare" },
      { name: "Tassin-la-Demi-Lune", slug: "tassin-la-demi-lune" },
      { name: "Ternay", slug: "ternay" },
      { name: "Thizy-les-Bourgs", slug: "thizy-les-bourgs" },
      { name: "Tupin-et-Semons", slug: "tupin-et-semons" },
      { name: "Vaugneray", slug: "vaugneray" },
      { name: "Vernaison", slug: "vernaison" },
      { name: "Villefranche-sur-Saône", slug: "villefranche-sur-Saone" },
    ],
  },
  {
    region: "Ain",
    numero: "01",
    city: [
      { name: "Ambérieu-en-Bugey", slug: "amberieu-en-bugey" },
      { name: "Anglefort", slug: "anglefort" },
      { name: "Attignat", slug: "attignat" },
      { name: "Balan", slug: "balan" },
      { name: "Bellegarde-sur-Valserine", slug: "bellegarde-sur-valserine" },
      { name: "Belley", slug: "belley" },
      { name: "Beynost", slug: "beynost" },
      { name: "Billiat", slug: "billiat" },
      { name: "Bourg-en-Bresse", slug: "bourg-en-bresse" },
      { name: "Brégnier-Cordon", slug: "bregnier-cordon" },
      { name: "Brens", slug: "brens" },
      { name: "Briord", slug: "briord" },
      { name: "Ceyzériat", slug: "ceyzeriat" },
      { name: "Challex", slug: "challex" },
      { name: "Chanay", slug: "chanay" },
      { name: "Châtillon-sur-Chalaronne", slug: "chatillon-sur-chalaronne" },
      { name: "Collonges", slug: "collonges" },
      { name: "Corbonod", slug: "corbonod" },
      { name: "Cressin-Rochefort", slug: "cressin-rochefort" },
      { name: "Culoz", slug: "culoz" },
      { name: "Gex", slug: "gex" },
      { name: "Groslée-Saint-Benoit", slug: "groslee-saint-benoit" },
      { name: "Injoux-Génissiat", slug: "injoux-genissiat" },
      { name: "Hauteville-Lompnes", slug: "hauteville-lompnes" },
      { name: "Lagnieu", slug: "lagnieu" },
      { name: "Lavours", slug: "lavours" },
      { name: "Léaz", slug: "leaz" },
      { name: "Lhuis", slug: "lhuis" },
      { name: "Loyettes", slug: "loyettes" },
      { name: "Massignieu-de-Rives", slug: "massignieu-de-rives" },
      { name: "Meximieux", slug: "meximieux" },
      { name: "Miribel", slug: "miribel" },
      { name: "Montagnieu", slug: "montagnieu" },
      { name: "Murs-et-Gélignieux", slug: "murs-et-gelignieux" },
      { name: "Nantua", slug: "nantua" },
      { name: "Neyron", slug: "neyron" },
      { name: "Niévroz", slug: "nievroz" },
      { name: "Oyonnax", slug: "oyonnax" },
      { name: "Parves et Nattages", slug: "parves-et-nattages" },
      { name: "Peyrieu", slug: "peyrieu" },
      { name: "Pont-d'Ain", slug: "pont-d-ain" },
      { name: "Pougny", slug: "pougny" },
      { name: "Replonges", slug: "replonges" },
      { name: "Saint-Étienne-du-Bois", slug: "saint-etienne-du-bois" },
      { name: "Saint-Genis-Pouilly", slug: "saint-genis-pouilly" },
      { name: "Saint-Sorlin-en-Bugey", slug: "saint-sorlin-en-bugey" },
      { name: "Saint-Vulbas", slug: "saint-vulbas" },
      { name: "Saint-Maurice-de-Beynost", slug: "saint-maurice-de-beynost" },
      { name: "Saint-Maurice-de-Gourdans", slug: "saint-maurice-de-gourdans" },
      { name: "Sault-Brénaz", slug: "sault-brenaz" },
      { name: "Serrières-de-Briord", slug: "serrieres-de-briord" },
      { name: "Seyssel", slug: "seyssel" },
      { name: "Surjoux-Lhopital", slug: "surjoux-lhopital" },
      { name: "Thoiry", slug: "thoiry" },
      { name: "Thil", slug: "thil" },
      { name: "Trévoux", slug: "trevoux" },
      { name: "Valserhône", slug: "valserhône" },
      { name: "Villars-les-Dombes", slug: "villars-les-dombes" },
      { name: "Virignin", slug: "virignin" },
      { name: "Villebois", slug: "villebois" },
      { name: "Vonnas", slug: "vonnas" },
    ],
  },
  {
    region: "Isère",
    numero: "38",
    city: [
      { name: "Anthon", slug: "anthon" },
      { name: "Aoste", slug: " aoste" },
      { name: "Avenières", slug: "les-avenières" },
      { name: "Bièvre", slug: "bievre" },
      { name: "Bouchage", slug: "le-bouchage" },
      { name: "Bourgoin-Jallieu", slug: "bourgoin-jallieu" },
      { name: "Bouvesse-Quirieu", slug: "bouvesse-quirieu" },
      { name: "Brangues", slug: "brangues" },
      { name: "Chartreuse-Guiers", slug: "chartreuse-guiers" },
      { name: "Charvieu-Chavagneux", slug: "charvieu-chavagneux" },
      { name: "Chasse-sur-Rhône", slug: "chasse-sur-rhone" },
      { name: "Chavanoz", slug: "chavanoz" },
      { name: "Chonas-l'Amballan", slug: "chonas-l-amballan" },
      { name: "Creys-Mépieu", slug: "creys-mepieu" },
      { name: "Échirolles", slug: "echirolles" },
      { name: "Fontaine-Seyssinet", slug: "fontaine-seyssinet" },
      { name: "Fontaine-Vercors", slug: "fontaine-vercors" },
      { name: "Grésivaudan", slug: "gresivaudan" },
      { name: "Hières-sur-Amby", slug: "hieres-sur-amby" },
      { name: "La Balme-les-Grottes", slug: "la-balme-les-grottes" },
      { name: "La Verpillière", slug: "la-verpilliere" },
      { name: "La Tour-du-Pin", slug: "la-tour-du-pin" },
      { name: "L'Isle-d'Abeau", slug: "l-isle-d-abeau" },
      { name: "Grand-Lemps", slug: "le-grand-lemps" },
      { name: "Pont-de-Claix", slug: "pont-de-claix" },
      { name: "Grenoble", slug: "grenoble" },
      { name: "Matheysine-Trièves", slug: "matheysine-trieves" },
      { name: "Meylan", slug: "meylan" },
      { name: "Montalieu-Vercieu", slug: "montalieu-vercieu" },
      { name: "Morestel", slug: "morestel" },
      { name: "Oisans-Romanche", slug: "oisans-romanche" },
      { name: "Péage-de-Roussillon", slug: "peage-de-roussillon" },
      { name: "Porcieu-Amblagnieu", slug: "porcieu-amblagnieu" },
      { name: "Reventin-Vaugris", slug: "reventin-vaugris" },
      { name: "Roches-de-Condrieu", slug: "voiron" },
      { name: "Roussillon", slug: "roussillon" },
      { name: "Sablons", slug: "sablons" },
      { name: "Saint-Alban-du-Rhône", slug: "saint-alban-du-rhone" },
      { name: "Saint-Clair-du-Rhône", slug: "saint-clair-du-rhone" },
      { name: "Saint-Martin-d'Hères", slug: "saint-martin-d-heres" },
      { name: "Saint-Maurice-l'Exil", slug: "saint-maurice-l-exil" },
      { name: "Saint-Prim", slug: "saint-prim" },
      { name: "Saint-Romain-de-Jalionas", slug: "saint-romain-de-jalionas" },
      { name: "Saint-Victor-de-Morestel", slug: "saint-victor-de-morestel" },
      { name: "Salaise-sur-Sanne", slug: "salaise-sur-sanne" },
      { name: "Seyssuel", slug: "seyssuel" },
      { name: "Tullins", slug: "tullins" },
      { name: "Vertrieu", slug: "vertrieu" },
      { name: "Veyrins-Thuellin", slug: "veyrins-thuellin" },
      { name: "Vienne", slug: "vienne" },
      { name: "Villette-d'Anthon", slug: "villette-d-anthon" },
      { name: "Voiron", slug: "voiron" },
    ],
  },
  {
    region: "Drôme",
    numero: "26",
    city: [
      { name: "Ancône", slug: "ancone" },
      { name: "Andancette", slug: "andancette" },
      { name: "Bourg-de-Péage", slug: "bourg-de-peage" },
      { name: "Bourg-lès-Valence", slug: "bourg-les-valence" },
      { name: "Châteauneuf-du-Rhône", slug: "chateauneuf-du-rhone" },
      { name: "Châtillon-en-Diois", slug: "chatillon-en-diois" },
      { name: "Chatuzange-le-Goubet", slug: "chatuzange-le-goubet" },
      { name: "Crest", slug: "crest" },
      { name: "Crozes-Hermitage", slug: "crozes-hermitage" },
      { name: "Dieulefit", slug: "dieulefit" },
      { name: "Donzère", slug: "donzere" },
      { name: "Érôme", slug: "erome" },
      { name: "Étoile-sur-Rhône", slug: "etoile-sur-rhone" },
      { name: "Gervans", slug: "gervans" },
      { name: "Grignan", slug: "grignan" },
      { name: "La Coucourde", slug: "la-coucourde" },
      { name: "La Roche-de-Glun", slug: "la-roche-de-glun" },
      { name: "Laveyron", slug: "laveyron" },
      { name: "Les Tourrettes", slug: "les-tourrettes" },
      { name: "Livron-sur-Drôme", slug: "livron-sur-drome" },
      { name: "Loriol-sur-Drôme", slug: "loriol-sur-drome" },
      { name: "Mercurol-Veaunes", slug: "mercurol-veaunes" },
      { name: "Montélimar", slug: "montelimar" },
      { name: "Nyons", slug: "nyons" },
      { name: "Ponsas", slug: "ponsas" },
      { name: "Portes-lès-Valence", slug: "portes-les-valence" },
      { name: "Pierrelatte", slug: "pierrelatte" },
      { name: "Romans-sur-Isère", slug: "romans-sur-isere" },
      {
        name: "Saint-Donat-sur-l'Herbasse",
        slug: "saint-donat-sur-l-herbasse",
      },
      { name: "Saint-Rambert-d'Albon", slug: "saint-rambert-d-albon" },
      { name: "Saint-Vallier", slug: "saint-vallier" },
      { name: "Saulce-sur-Rhône", slug: "saulce-sur-rhone" },
      { name: "Savasse", slug: "savasse" },
      { name: "Serves-sur-Rhône", slug: "serves-sur-rhone" },
      { name: "Tain-l'Hermitage", slug: "tain-l-hermitage" },
      { name: "Le Tricastin", slug: "tricastin" },
      { name: "Valence", slug: "valence" },
    ],
  },
  {
    region: "Ardèche",
    numero: "07",
    city: [
      { name: "Annonay", slug: "annonay" },
      { name: "Arras-sur-Rhône", slug: "arras-sur-rhone" },
      { name: "Aubenas", slug: "aubenas" },
      { name: "Baix", slug: "baix" },
      { name: "Beauchastel", slug: "beauchastel" },
      { name: "Berg-Helvie", slug: "berg-helvie" },
      { name: "Bourg-Saint-Andéol", slug: "bourg-saint-andeol" },
      { name: "Champagne", slug: "champagne" },
      { name: "Charmes-sur-Rhône", slug: "charmes-sur-rhone" },
      { name: "Châteaubourg", slug: "chateaubourg" },
      { name: "Cornas", slug: "cornas" },
      { name: "Cruas", slug: "cruas" },
      { name: "Glun", slug: "glun" },
      { name: "Guilherand-Granges", slug: "guilherand-granges" },
      { name: "Haut-Eyrieux", slug: "haut-eyrieux" },
      { name: "Lamastre", slug: "lamastre" },
      { name: "Thueyts", slug: "thueyts" },
      { name: "La Voulte-sur-Rhône", slug: "la-voulte-sur-rhone" },
      { name: "Largentière", slug: "largentiere" },
      { name: "Le Cheylard", slug: "le-cheylard" },
      { name: "Lemps", slug: "lemps" },
      { name: "Le Pouzin", slug: "le-pouzin" },
      { name: "Le Teil", slug: "le-teil" },
      { name: "Les Vans", slug: "les-vans" },
      { name: "Limony", slug: "limony" },
      { name: "Mauves", slug: "mauves" },
      { name: "Meysse", slug: "meysse" },
      { name: "Ozon", slug: "ozon" },
      { name: "Peyraud", slug: "peyraud" },
      { name: "Privas", slug: "privas" },
      { name: "Rochemaure", slug: "rochemaure" },
      { name: "Rompon", slug: "rompon" },
      { name: "Saint-Désirat", slug: "saint-desirat" },
      { name: "Saint-Georges-les-Bains", slug: "saint-georges-les-bains" },
      { name: "Saint-Jean-de-Muzols", slug: "saint-jean-de-muzols" },
      { name: "Saint-Just-d'Ardèche", slug: "saint-just-d-ardeche" },
      { name: "Saint-Marcel-d'Ardèche", slug: "saint-marcel-d-ardeche" },
      { name: "Saint-Montan", slug: "saint-montan" },
      { name: "Saint-Péray", slug: "saint-peray" },
      { name: "Sarras", slug: "sarras" },
      { name: "Serrières", slug: "serrieres" },
      { name: "Soyons", slug: "soyons" },
      { name: "Thueyts", slug: "thueyts" },
      { name: "Tournon-sur-Rhône", slug: "tournon-sur-rhone" },
      { name: "Vallon-Pont-d'Arc", slug: "vallon-pont-d-arc" },
      { name: "Vion", slug: "vion" },
      { name: "Viviers", slug: "viviers" },
    ],
  },
  {
    region: "Savoie",
    numero: "73",
    city: [
      { name: "Aix-les-Bains", slug: "aix-les-bains" },
      { name: "Albertville", slug: "albertville" },
      { name: "Bourg-Saint-Maurice", slug: "bourg-saint-maurice" },
      { name: "Chambéry", slug: "chambéry" },
      { name: "Champagneux", slug: "champagneux" },
      { name: "Chanaz", slug: "chanaz" },
      { name: "Jongieux", slug: "jongieux" },
      { name: "La Balme", slug: "la-balme" },
      { name: "La Motte-Servolex", slug: "la-motte-servolex" },
      { name: "La Ravoire", slug: "la-ravoire" },
      { name: "Lucey", slug: "lucey" },
      { name: "Pont-de-Beauvoisin", slug: "le-pont-de-beauvoisin" },
      { name: "Modane", slug: "modane" },
      { name: "Montmélian", slug: "montmelian" },
      { name: "Motz", slug: "motz" },
      { name: "Moûtiers", slug: "moutiers" },
      { name: "Ruffieux", slug: "ruffieux" },
      { name: "Saint-Alban-Leysse", slug: "saint-alban-leysse" },
      { name: "Saint-Genix-les-Villages", slug: "saint-genix-les-villages" },
      { name: "Saint-Jean-de-Maurienne", slug: "saint-jean-de-maurienne" },
      { name: "Saint-Pierre-d'Albigny", slug: "saint-pierre-d-albigny" },
      { name: "Serrières-en-Chautagne", slug: "serrieres-en-chautagne" },
      { name: "Ugine", slug: "ugine" },
      { name: "Vions", slug: "vions" },
      { name: "Yenne", slug: "yenne" },
    ],
  },
  {
    region: "Haute-Savoie",
    numero: "74",
    city: [
      { name: "Annecy", slug: "annecy" },
      { name: "Annemasse", slug: "annemasse" },
      { name: "Anthy-sur-Léman", slug: "anthy-sur-leman" },
      { name: "Bassy", slug: "bassy" },
      { name: "Bonneville", slug: "bonneville" },
      { name: "Challonges", slug: "challonges" },
      { name: "Chens-sur-Léman", slug: "chens-sur-leman" },
      { name: "Chevrier", slug: "chevrier" },
      { name: "Clarafond-Arcine", slug: "clarafond-arcine" },
      { name: "Collonges-sous-Salève", slug: "collonges-sous-saleve" },
      { name: "Cluses", slug: "cluses" },
      { name: "Éloise", slug: "eloise" },
      { name: "Evian-les-bains", slug: "evian-les-bains" },
      { name: "Excenevex", slug: "excenevex" },
      { name: "Faverges-Seythenex", slug: "faverges-seythenex" },
      { name: "Franclens", slug: "franclens" },
      { name: "Gaillard", slug: "gaillard" },
      { name: "Chamonix", slug: "chamonix" },
      { name: "La Roche-sur-foron", slug: "la-roche-sur-foron" },
      { name: "Lugrin", slug: "lugrin" },
      { name: "Margencel", slug: "margencel" },
      { name: "Maxilly-sur-Léman", slug: "maxilly-sur-leman" },
      { name: "Meillerie", slug: "meillerie" },
      { name: "Messery", slug: "messery" },
      { name: "Nernier", slug: "nernier" },
      { name: "Neuvecelle", slug: "neuvecelle" },
      { name: "Publier", slug: "publier" },
      { name: "Rumilly", slug: "rumilly" },
      { name: "Saint-Germain-sur-Rhône", slug: "saint-germain-sur-rhone" },
      { name: "Saint-Gingolph", slug: "saint-gingolph" },
      { name: "Saint-Julien-en-Genevois", slug: "saint-julien-en-Genevois" },
      { name: "Sallanches", slug: "sallanches" },
      { name: "Sciez", slug: "sciez" },
      { name: "Seynod", slug: "seynod" },
      { name: "Seyssel", slug: "seyssel" },
      { name: "Thonon-les-Bains", slug: "thonon-les-Bains" },
      { name: "Viry", slug: "viry" },
      { name: "Vulbens", slug: "vulbens" },
      { name: "Yvoire", slug: "yvoire" },
    ],
  },
  {
    region: "Loire",
    numero: "42",
    city: [
      { name: "Andrézieux-Bouthéon", slug: "andrezieux-boutheon" },
      { name: "Boën-sur-Lignon", slug: "boen-sur-lignon" },
      { name: "Chambles", slug: "chambles" },
      { name: "Charlieu", slug: "charlieu" },
      { name: "Chavanay", slug: "chavanay" },
      { name: "Feurs", slug: "feurs" },
      { name: "Firminy", slug: "firminy" },
      { name: "La Ricamarie", slug: "la-ricamarie" },
      { name: "La Talaudière", slug: "la-talaudiere" },
      { name: "Le Bessat", slug: "le-bessat" },
      { name: "Le Coteau", slug: "le-coteau" },
      { name: "Montbrison", slug: "montbrison" },
      { name: "Planfoy", slug: "planfoy" },
      { name: "Renaison", slug: "renaison" },
      { name: "Rive-de-Gier", slug: "rive-de-gier" },
      { name: "Roanne", slug: "roanne" },
      { name: "Roche-la-Molière", slug: "roche-la-moliere" },
      { name: "Saint-Chamond", slug: "saint-chamond" },
      { name: "Saint-Etienne", slug: "saint-etienne" },
      { name: "Saint-Genest-Lerp", slug: "saint-genest-lerp" },
      { name: "Saint-Genest-Malifaux", slug: "saint-genest-malifaux" },
      { name: "Saint-Jean-Bonnefonds", slug: "saint-jean-bonnefonds" },
      { name: "Saint-Just-Saint-Rambert", slug: "saint-just-saint-rambert" },
      { name: "Saint-Michel-sur-Rhône", slug: "saint-michel-sur-rhone" },
      { name: "Saint-Pierre-de-Boeuf", slug: "saint-pierre-de-boeuf" },
      { name: "Saint-Priest-en-Jarez", slug: "saint-priest-en-jarez" },
      { name: "Saint-Romain-les-Atheux", slug: "saint-romain-les-atheux" },
      { name: "La Tarentaise", slug: "tarentaise" },
      { name: "Sorbiers", slug: "sorbiers" },
      { name: "Veauche", slug: "veauche" },
      { name: "Vérin", slug: "verin" },
      { name: "Villars", slug: "villars" },
    ],
  },
  {
    region: "Haute-Loire",
    numero: "43",
    city: [
      { name: "Aurec-sur-Loire", slug: "aurec-sur-loire" },
      { name: "Bas-en-Basset", slug: "bas-en-basset" },
      { name: "Boutières", slug: "boutieres" },
      { name: "Brioude", slug: "brioude" },
      { name: "Emblavez-et-Meygal", slug: "emblavez-et-meygal" },
      { name: "Langeac", slug: "langeac" },
      {
        name: "Puy-en-Velay",
        slug: "puy-en-velay",
        region: "Haute-Loire",
        preName: "au",
        preDep: "la",
      },
      { name: "Sainte-Sigolène", slug: "sainte-sigolene" },
      { name: "Mézenc", slug: "mezenc" },
      { name: "Monistrol-sur-Loire", slug: "monistrol-sur-loire" },
      { name: "Mazeyrat-d'Allier", slug: "mazeyrat-d-allier" },
      { name: "Craponne-sur-Arzon", slug: "craponne-sur-arzon" },
      { name: "Saint-Paulien", slug: "saint-paulien" },
      { name: "Sainte-Florine", slug: "sainte-florine" },
      { name: "Cussac-sur-Loire", slug: "cussac-sur-loire" },
      { name: "Yssingeaux", slug: "yssingeaux" },
    ],
  },
];
